// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbfkqjqesrsntoggwuyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiZmtxanFlc3JzbnRvZ2d3dXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDkzODUsImV4cCI6MjA1OTA4NTM4NX0.hkG_2CzTUsbxA7t7l1CuFGXnMevydvPOMCgKcvt9PqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);